version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/operator-docker-compose
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  split: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"